# Site-wide settings
title: "My Jekyll Blog"
description: "A simple blog built with Jekyll"

# URL and baseurl for deployment
url: "https://hike-projects.github.io"  # Root URL of your GitHub Pages site
baseurl: "/Blogpage"  # The subfolder where your site is hosted                    # The subfolder where your site is hosted

# _config.yml
permalink: /Blogpage/:year/:month/:day/:title/  # Correct URL structure for posts

# Standard Jekyll permalink format

excerpt_separator: "\n\n<!--more-->\n\n"  # This separates the preview content from the full content

# Optional: To serve CSS assets and other assets correctly
assets:
  css_dir: "assets/css"  # You can specify the directory for CSS if desired (optional)

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include files in the build
include:
  - "_posts"  # Include all posts in the build

# Additional configurations (if needed)
# You can add more settings like navigation links, Google Analytics, etc.
