# Site-wide settings
title: "My Jekyll Blog"
description: "A simple blog built with Jekyll"

# URL and baseurl for deployment
url: "https://username.github.io"  # Replace with your domain or GitHub Pages URL
baseurl: "/my-blog"  # Use empty string if the site is hosted at the root

# Optional: To serve CSS assets and other assets correctly
assets:
  css_dir: "assets/css"  # You can specify the directory for CSS if desired (optional)

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include files in the build
include:
  - "_posts"  # Include all posts in the build

# Social links (optional)
social_links:
  twitter: "https://twitter.com/username"
  instagram: "https://instagram.com/username"
